theme = "tokyotransparent"

[editor]
line-number = "relative"

[editor.cursor-shape]
insert = "bar"
normal = "block"
select = "underline"

[editor.lsp]
auto-signature-help = false

[editor.file-picker]
hidden = false

[keys.normal]
C-m=":run-shell-command odin run ."

[keys.insert]
C-p = "signature_help"
